name: Test 32-bit DLL Load

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
    
    - name: Build test DLL (Win32, no forwarders)
      run: |
        cl /c /MT /O2 /GS- /Fo"test_dll.obj" test_dll.cpp
        link /DLL /OUT:"steam_api.dll" /MACHINE:X86 /SUBSYSTEM:WINDOWS /NXCOMPAT:NO /SAFESEH:NO test_dll.obj
    
    - name: Upload test DLL
      uses: actions/upload-artifact@v4
      with:
        name: test_steam_api_Win32
        path: steam_api.dll
